Post: Purpose of Django's SECRET_KEY
awsomsauce/website pull request #5
Opened 2020-08-23 18:26 UTC by SanketDG

Looking for comments on the rough outline @ankitsurkar @mihirsn

2020-08-26 18:05 UTC, mihirsn requested changes

2020-08-26 18:05 UTC, mihirsn commented on content/post/django-secret-key.md
> +title: "What is the purpose of SECRET_KEY in Django?"
What about title: Purpose of SECRET_KEY in Django

2020-08-26 18:05 UTC, mihirsn commented on content/post/django-secret-key.md
> +It's also used as the when a user logs in and the session token is generated.
can be converted to - It's also used when a user logs in and the session token is generated

2020-08-26 18:15 UTC, mihirsn commented
I think we can add one more point about its use : such that in lot of applications developers keep it hard coded in settings.py file instead we can set environment variable from where we can access it.

2020-08-26 18:20 UTC, mihirsn commented on content/post/django-secret-key.md
> +4.0 Breaking changes
___Django___ 4.0 Breaking changes ?

2020-08-26 18:21 UTC, mihirsn commented on content/post/django-secret-key.md
> +4.0 Breaking changes
___Django___ 4.0 Breaking changes ?

2020-08-29 11:46 UTC, SanketDG commented on content/post/django-secret-key.md
> +title: "What is the purpose of SECRET_KEY in Django?"
Will change

2020-09-01 10:35 UTC, merged